import { useEffect, useRef, useState } from 'react';
import { Icon } from './ui';
type State = 'idle' | 'requesting' | 'waiting' | 'confirmed' | 'error';
type Props = { address: string; onClose: () => void; onConfirmed?: (txid: string) => void };
const keyFor = (address: string) => `ripcord:faucet:${address}`;
export function FaucetModal({ address, onClose, onConfirmed }: Props) {
  const [state, setState] = useState<State>('idle'); const [message, setMessage] = useState(''); const panel = useRef<HTMLElement>(null); const close = useRef<HTMLButtonElement>(null); const abortRef = useRef<AbortController | null>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; close.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); onClose(); return; } if (event.key !== 'Tab' || !panel.current) return; const nodes = [...panel.current.querySelectorAll<HTMLElement>('button,[href],input,textarea,[tabindex]:not([tabindex="-1"])')]; if (!nodes.length) return; const first = nodes[0], last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', key); return () => { document.removeEventListener('keydown', key); abortRef.current?.abort(); previous?.focus(); }; }, [onClose]);
  const waitForConfirmation = async (txid: string) => { const started = Date.now(); const controller = new AbortController(); abortRef.current = controller; setState('waiting'); while (!controller.signal.aborted) { try { const response = await fetch('/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, signal: controller.signal, body: JSON.stringify({ jsonrpc: '2.0', id: Date.now(), method: 'getrawtransaction', params: [txid, true] }) }); const payload = await response.json() as { result?: { confirmations?: number }; error?: { message?: string } }; if ((payload.result?.confirmations ?? 0) > 0) { setState('confirmed'); setMessage(`Funding confirmed: ${txid} · ${payload.result!.confirmations} confirmation(s)`); onConfirmed?.(txid); return; } if (payload.error && !/no such mempool|not found/i.test(payload.error.message ?? '')) throw new Error(payload.error.message ?? 'Bitcoin RPC lookup failed'); setMessage(`Funding broadcast: ${txid} · waiting for an L1 confirmation (${Math.floor((Date.now() - started) / 1000)}s elapsed)`); } catch (error) { if (controller.signal.aborted) return; setState('error'); setMessage(error instanceof Error ? error.message : String(error)); return; } await new Promise(resolve => setTimeout(resolve, 5000)); } };
  useEffect(() => { const saved = localStorage.getItem(keyFor(address)); if (saved && /^[0-9a-f]{64}$/i.test(saved)) { setMessage(`Resuming funding broadcast: ${saved} · checking live confirmation`); void waitForConfirmation(saved); } }, [address]);
  const request = async () => { setState('requesting'); setMessage(''); try { const response = await fetch('/faucet/api/faucet', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ address, amountBtc: 0.5 }) }); const text = await response.text(); let data: unknown; try { data = JSON.parse(text); } catch { data = null; } if (!response.ok) throw new Error(typeof data === 'object' && data && 'error' in data ? String((data as { error: unknown }).error) : text || `Faucet HTTP ${response.status}`); const txid = typeof data === 'object' && data && 'txid' in data ? String((data as { txid: unknown }).txid) : ''; if (!/^[0-9a-f]{64}$/i.test(txid)) throw new Error('Faucet response did not include a valid funding txid'); localStorage.setItem(keyFor(address), txid); setMessage(`Funding broadcast: ${txid} · waiting for an L1 confirmation`); await waitForConfirmation(txid); } catch (error) { setState('error'); setMessage(error instanceof Error ? error.message : String(error)); } };
  const buttonLabel = state === 'requesting' ? 'Requesting…' : state === 'waiting' ? 'Waiting for confirmation…' : state === 'confirmed' ? 'Confirmed' : 'Request 0.5 regtest BTC';
  return <div className="sheet-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><aside ref={panel} className="proof-sheet" role="dialog" aria-modal="true" aria-labelledby="faucet-title"><header><div><p className="eyebrow">Regtest funding</p><h2 id="faucet-title">Request faucet funds</h2></div><button ref={close} aria-label="Close faucet" onClick={onClose}><Icon name="close" /></button></header><div className="flow-body"><p>The faucet sends 0.5 regtest BTC to your L1 settlement address. After it confirms, Ripcord will deposit 40,000 sats into your vault, wait for that deposit to confirm, then create your first VTXO.</p><p className="flow-note">The test network produces Bitcoin blocks automatically about every 10 minutes. You can close this panel and return later. Your transaction is saved and setup will resume when it confirms.</p><code>{address}</code><button className="test-pull" disabled={state === 'requesting' || state === 'waiting' || state === 'confirmed'} onClick={() => void request()}>{buttonLabel}</button>{message && <p role="status" className={state === 'error' ? 'inline-error' : state === 'confirmed' ? 'flow-note' : 'inline-note'}>{message}</p>}{state === 'waiting' && <button className="secondary-action" onClick={onClose}>Close and check later</button>}</div></aside></div>;
}
