import { useEffect, useRef } from 'react';
import type { PaymentReceipt } from '@ripcord/core/types';
import { Icon, truncate } from './ui';
export function ProofSheet({ receipt, onClose }: { receipt: PaymentReceipt | null; onClose: () => void }) {
  const panel = useRef<HTMLElement>(null); const close = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (!receipt) return; const previous = document.activeElement as HTMLElement | null; close.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); onClose(); return; } if (event.key !== 'Tab' || !panel.current) return; const nodes = [...panel.current.querySelectorAll<HTMLElement>('button,[href],[tabindex]:not([tabindex="-1"])')]; if (!nodes.length) return; const first = nodes[0]; const last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', key); return () => { document.removeEventListener('keydown', key); previous?.focus(); }; }, [receipt, onClose]);
  if (!receipt) return null;
  return <div className="sheet-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><aside ref={panel} className="proof-sheet" role="dialog" aria-modal="true" aria-labelledby="proof-title"><header><div><p className="eyebrow">Cryptographic receipt</p><h2 id="proof-title">Proof chain</h2></div><button ref={close} aria-label="Close proof" onClick={onClose}><Icon name="close" /></button></header><div className="proof-chain"><ProofStep label="Transaction" value={truncate(receipt.txHash, 14, 10)} detail={`epoch ${receipt.epoch} · code ${receipt.code}`} /><ProofStep label="HAT" value={receipt.hat ? truncate(receipt.hat.proof, 14, 10) : 'Unavailable'} detail={receipt.hat ? 'daemon commitment included' : 'not fetched'} /><ProofStep label="Verkle" value={receipt.rip?.hatInStateDiff ? 'HAT found in state diff' : 'Not verified'} detail="normalized inclusion comparison" /><ProofStep label="RIP chain" value={receipt.rip ? receipt.rip.chainLength === 0 ? 'self-proof' : `${receipt.rip.chainLength} epochs` : 'Unavailable'} detail={receipt.rip ? `origin ${receipt.rip.originEpoch} → final ${receipt.rip.finalEpoch}` : 'not fetched'} /><ProofStep label="Final root" value={receipt.rip ? truncate(receipt.rip.finalRoot, 14, 10) : 'Unavailable'} detail="daemon-attested; encoding preserved" /></div><div className="proof-caveats"><p><strong>PSBT payload</strong> unavailable on regtest; HAT is not recomputed locally.</p><p><strong>L1 anchor</strong> not populated in sampled regtest proofs.</p></div></aside></div>;
}
function ProofStep({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="proof-step"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
